### ISSUE TITLE
Cannot Add k8s Cluster

### ISSUE THREAD

**Issue by lladhibhutall** [vmware/mangle#32]
**Describe the bug**
Not able to add k8s cluster to mangle. Mangle is running on Openshift on the same cluster and namespace.
**To Reproduce**
1. Go to Endpoint >> Kubernetes Cluster
2. Click on `+ K8S Cluster`
3. Add any name; add credential(Its running on same cluster); add `default` as namespace

**Expected behavior**
Should add K8s cluster to `Endpoints`

**Error Output**
```
K8SServerError: Error from server (Forbidden): namespaces "default" is forbidden: User "system:serviceaccount:namespace:default" cannot get namespaces in the namespace "default": no RBAC policy matched
```

**Comment by ashrimalivmware** [comment]
Hi @lladhibhutall ,

Can you please provide the logs from mangle application?

Thanks,
-Avinash

**Comment by lladhibhutall** [comment]
@ashrimalivmware The whole trace from OpenShift logs
```
  | 2020-04-23   09:44:53.733 [https-jsse-nio-8443-exec-4] INFO com.vmware.mangle.services.EndpointService.testEndpointConnection   (133) - Start execution of testEndpointConnection() method
-- | --
  | 2020-04-23   09:44:53.746 [https-jsse-nio-8443-exec-4] INFO   com.vmware.mangle.utils.clients.kubernetes.KubernetesCommandLineClient.getClient   (54) - Creating kubernetes commandline client
  | 2020-04-23   09:44:53.851 [https-jsse-nio-8443-exec-4] ERROR com.vmware.mangle.utils.exceptions.handler.CustomizedResponseEntityExceptionHandler.handleMangleException   (109) - Error Code : FIK8S01, Error Message : K8SServerError: Error from server (Forbidden): namespaces "default" is forbidden: User "system:serviceaccount:namespace:default" cannot get namespaces in the namespace "default": no RBAC policy matched
  |  
  | com.vmware.mangle.utils.exceptions.MangleException:   null
  | at   com.vmware.mangle.utils.clients.kubernetes.KubernetesCommandLineClient.validateK8SCommandOutput(KubernetesCommandLineClient.java:168)   ~[mangle-utils-2.0.0.jar!/:2.0.0]
  | at   com.vmware.mangle.utils.clients.kubernetes.KubernetesCommandLineClient.testConnection(KubernetesCommandLineClient.java:155)   ~[mangle-utils-2.0.0.jar!/:2.0.0]
  | at   com.vmware.mangle.services.EndpointService.testEndpointConnection(EndpointService.java:147)   ~[classes!/:2.0.0]
  | at   com.vmware.mangle.services.controller.EndpointController.endpointTestConnection(EndpointController.java:377)   ~[classes!/:2.0.0]
  | at   sun.reflect.GeneratedMethodAccessor224.invoke(Unknown Source) ~[?:?]
  | at   sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)   ~[?:1.8.0-internal]
  | at   java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0-internal]
  | at   org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)   ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)   ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)   ~[spring-webmvc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)   ~[spring-webmvc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)   ~[spring-webmvc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)   ~[spring-webmvc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)   [spring-webmvc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)   [spring-webmvc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)   [spring-webmvc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)   [spring-webmvc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   javax.servlet.http.HttpServlet.service(HttpServlet.java:660)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)   [spring-webmvc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   javax.servlet.http.HttpServlet.service(HttpServlet.java:741)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)   [tomcat-embed-websocket-9.0.19.jar!/:9.0.19]
  | at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   com.vmware.mangle.services.config.CORSFilter.doFilter(CORSFilter.java:74)   [classes!/:2.0.0]
  | at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)   [spring-boot-actuator-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
  | at   org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)   [spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)   [spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:155)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)   [spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)   [spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)   [spring-security-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
  | at   org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)   [spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)   [spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)   [spring-boot-actuator-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
  | at   org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)   [spring-boot-actuator-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)   [spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)   [spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)   [spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:607)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)   [?:1.8.0-internal]
  | at   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)   [?:1.8.0-internal]
  | at   org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)   [tomcat-embed-core-9.0.19.jar!/:9.0.19]
  | at   java.lang.Thread.run(Thread.java:748) [?:1.8.0-internal]
  | 2020-04-23   09:45:00.000 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.services.tasks.executor.TaskExecutor.updateTaskInfo (402) -   Updating Task. Current task status: IN_PROGRESS
  | 2020-04-23   09:45:00.240 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.services.events.listener.MangleEventListener.handle (54) -   Modified Task: com.vmware.mangle.cassandra.model.tasks.FaultTask With Id:   2a52dca3-30f7-43bf-8136-9f57552f0f6b
  | 2020-04-23   09:45:00.700 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.task.framework.helpers.AbstractCommandExecutionTaskHelper.checkInjectionPrequisitesStage   (137) - Completed Prerequisite Check
  | 2020-04-23   09:45:00.700 [SystemResourceFaultTaskHelper-1587371377321] ERROR com.vmware.mangle.utils.helpers.security.DecryptFields.decrypt   (52) - Decrypting privateKey field failed with exception. Text provided as   input cannot be decrypted using Mangle's default format. Skipped decryption
  | 2020-04-23   09:45:00.700 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.utils.clients.ssh.SSHUtils.putFile (90) - preparing the   host information for sftp.
  | 2020-04-23   09:45:00.700 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.utils.RemoteBase.getSession (83) - identity added
  | 2020-04-23   09:45:00.830 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.utils.clients.ssh.SSHUtils.cleanupSession (225) - Host   Session disconnected.
  | 2020-04-23   09:45:00.830 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.faults.plugin.tasks.helpers.SystemResourceFaultTaskHelper.prepareEndpoint   (144) - Copied Support Script File: cpuburn.sh to Remote Machine
  | 2020-04-23   09:45:00.831 [SystemResourceFaultTaskHelper-1587371377321] ERROR   com.vmware.mangle.utils.helpers.security.DecryptFields.decrypt (52) -   Decrypting privateKey field failed with exception. Text provided as input   cannot be decrypted using Mangle's default format. Skipped decryption
  | 2020-04-23   09:45:00.831 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.utils.clients.ssh.SSHUtils.runCommandReturningResult (156)   - Running Command ...
  | 2020-04-23   09:45:00.831 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.utils.RemoteBase.getSession (83) - identity added
  | 2020-04-23   09:45:01.914 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.task.framework.helpers.AbstractCommandExecutionTaskHelper.prepareTestmachineStage   (149) - Completed Test Machine Preperation
  | 2020-04-23   09:45:02.149 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.utils.clients.ssh.SSHUtils.runCommandReturningResult (156)   - Running Command ...
  | 2020-04-23   09:45:02.149 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.utils.RemoteBase.getSession (83) - identity added
  | 2020-04-23   09:45:03.232 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.task.framework.helpers.AbstractCommandExecutionTaskHelper.triggerFaultInjectionStage   (165) - Completed Fault Injection
  | 2020-04-23   09:45:03.471 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.services.tasks.executor.TaskExecutor.updateTaskInfo (402) -   Updating Task. Current task status: COMPLETED
  | 2020-04-23   09:45:03.721 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.services.events.listener.MangleEventListener.handle (54) -   Modified Task: com.vmware.mangle.cassandra.model.tasks.FaultTask With Id:   2a52dca3-30f7-43bf-8136-9f57552f0f6b
  | 2020-04-23   09:45:03.721 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.services.SchedulerService.getSchedulerDetailsById (60) -   Retrieving Scheduler details for Job = 2a52dca3-30f7-43bf-8136-9f57552f0f6b
  | 2020-04-23 09:45:03.746   [SystemResourceFaultTaskHelper-1587371377321] WARN   com.vmware.mangle.services.helpers.MetricProviderHelper.sendFaultEvent (78) -   Cannot find an active metric provider. Please check if the metric providers   are created and marked as Active
  | 2020-04-23   09:45:03.746 [SystemResourceFaultTaskHelper-1587371377321] WARN   com.vmware.mangle.services.helpers.MetricProviderHelper.sendFaultEvent (80) -   Cannot send events to Metric Provider
  | 2020-04-23   09:45:05.513 [hz._hzInstance_1_mangle.cached.thread-4] WARN   com.hazelcast.cluster.impl.TcpIpJoiner.log (49) - [192.168.15.172]:5701   [mangle] [3.11] Cannot resolve hostname   'mangle-service.mangle.svc.cluster.local'. Please make sure host is valid and   reachable.
  | 2020-04-23   09:46:00.001 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.services.tasks.executor.TaskExecutor.updateTaskInfo (402) -   Updating Task. Current task status: IN_PROGRESS
  | 2020-04-23   09:46:00.236 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.services.events.listener.MangleEventListener.handle (54) -   Modified Task: com.vmware.mangle.cassandra.model.tasks.FaultTask With Id:   2a52dca3-30f7-43bf-8136-9f57552f0f6b
  | 2020-04-23   09:46:00.709 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.task.framework.helpers.AbstractCommandExecutionTaskHelper.checkInjectionPrequisitesStage   (137) - Completed Prerequisite Check
  | 2020-04-23   09:46:00.709 [SystemResourceFaultTaskHelper-1587371377321] ERROR   com.vmware.mangle.utils.helpers.security.DecryptFields.decrypt (52) -   Decrypting privateKey field failed with exception. Text provided as input   cannot be decrypted using Mangle's default format. Skipped decryption
  | 2020-04-23   09:46:00.709 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.utils.clients.ssh.SSHUtils.putFile (90) - preparing the   host information for sftp.
  | 2020-04-23   09:46:00.709 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.utils.RemoteBase.getSession (83) - identity added
  | 2020-04-23   09:46:00.814 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.utils.clients.ssh.SSHUtils.cleanupSession (225) - Host   Session disconnected.
  | 2020-04-23   09:46:00.814 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.faults.plugin.tasks.helpers.SystemResourceFaultTaskHelper.prepareEndpoint   (144) - Copied Support Script File: cpuburn.sh to Remote Machine
  | 2020-04-23   09:46:00.815 [SystemResourceFaultTaskHelper-1587371377321] ERROR   com.vmware.mangle.utils.helpers.security.DecryptFields.decrypt (52) -   Decrypting privateKey field failed with exception. Text provided as input   cannot be decrypted using Mangle's default format. Skipped decryption
  | 2020-04-23   09:46:00.815 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.utils.clients.ssh.SSHUtils.runCommandReturningResult (156)   - Running Command ...
  | 2020-04-23   09:46:00.815 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.utils.RemoteBase.getSession (83) - identity added
  | 2020-04-23   09:46:01.891 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.task.framework.helpers.AbstractCommandExecutionTaskHelper.prepareTestmachineStage   (149) - Completed Test Machine Preperation
  | 2020-04-23   09:46:02.130 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.utils.clients.ssh.SSHUtils.runCommandReturningResult (156)   - Running Command ...
  | 2020-04-23   09:46:02.130 [SystemResourceFaultTaskHelper-1587371377321] INFO com.vmware.mangle.utils.RemoteBase.getSession   (83) - identity added
  | 2020-04-23   09:46:03.219 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.task.framework.helpers.AbstractCommandExecutionTaskHelper.triggerFaultInjectionStage   (165) - Completed Fault Injection
  | 2020-04-23   09:46:03.463 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.services.tasks.executor.TaskExecutor.updateTaskInfo (402) -   Updating Task. Current task status: COMPLETED
  | 2020-04-23   09:46:03.686 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.services.events.listener.MangleEventListener.handle (54) -   Modified Task: com.vmware.mangle.cassandra.model.tasks.FaultTask With Id:   2a52dca3-30f7-43bf-8136-9f57552f0f6b
  | 2020-04-23   09:46:03.687 [SystemResourceFaultTaskHelper-1587371377321] INFO   com.vmware.mangle.services.SchedulerService.getSchedulerDetailsById (60) -   Retrieving Scheduler details for Job = 2a52dca3-30f7-43bf-8136-9f57552f0f6b
  | 2020-04-23   09:46:03.712 [SystemResourceFaultTaskHelper-1587371377321] WARN   com.vmware.mangle.services.helpers.MetricProviderHelper.sendFaultEvent (78) -   Cannot find an active metric provider. Please check if the metric providers   are created and marked as Active
  | 2020-04-23   09:46:03.712 [SystemResourceFaultTaskHelper-1587371377321] WARN   com.vmware.mangle.services.helpers.MetricProviderHelper.sendFaultEvent (80) -   Cannot send events to Metric Provider
```

**Comment by ashrimalivmware** [comment]
Hi @lladhibhutall 
It look like an issue with the openshift instance which you are using. The error message also thrown by the server, for reference please follow the similar issue raised with openshift: https://github.com/openshift/console/issues/1377.

Thanks,
-Avinash

**Comment by lladhibhutall** [comment]
@ashrimalivmware even if I give it the namespace as the one where Mangle is running instead of default, it still gives me the RBAC error.

**Comment by ashrimalivmware** [comment]
Hi @lladhibhutall 

The issue is with the cluster you are using. Most probably the user which is mentioned in the config file is not admin that is why you are getting RBAC related issues.

Just for verification I have crated an Openshift 4.2 cluster and added it to Mangle with default namespace, and its working fine. (But with Admin User)

Can you please try again with Admin user?

Thanks,
-Avinash
