### ISSUE TITLE
Unable to Run Mangle Jar

### ISSUE THREAD

**Issue by lladhibhutall** [vmware/mangle#34]
**Describe the bug**
While trying to run the `mangle-services.jar` after building it gives error saying:

```
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.IllegalStateException: Unable to create the directory [C:\home\mangle\var\opt\mangle-tomcat] to use as the base directory
```

The user doesn't actually have access to the `/home` so its throwing the error, is there a way I can change the path of base dir for mangle?

**To Reproduce**
1. git clone mangle
2. run `mvn clean install`
3. cd `mangle-service/target`
4. run `java –jar mangle-services-.x.x.x-jar –D......`

**Expected behavior**
Should start server and able to run the mangle app on browser(localhost)

**Logs**
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-05-04 19:04:32.577 [main] ERROR com.vmware.mangle.utils.exceptions.handler.MangleUncaughtExceptionHandler.uncaughtException (67) - Uncaught exception caught in thread :main
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.IllegalStateException: Unable to create the directory [C:\home\mangle\var\opt\mangle-tomcat] to use as the base directory
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:157) ~[spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
        at com.vmware.mangle.MangleApplication.main(MangleApplication.java:36) [classes!/:2.0.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_74]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_74]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_74]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [mangle-services.jar:2.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [mangle-services.jar:2.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [mangle-services.jar:2.0.0]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [mangle-services.jar:2.0.0]
Caused by: java.lang.IllegalStateException: Unable to create the directory [C:\home\mangle\var\opt\mangle-tomcat] to use as the base directory
        at org.apache.catalina.startup.Tomcat.initBaseDir(Tomcat.java:815) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.startup.Tomcat.getServer(Tomcat.java:624) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.apache.catalina.startup.Tomcat.getService(Tomcat.java:557) ~[tomcat-embed-core-9.0.19.jar!/:9.0.19]
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:165) ~[spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:181) ~[spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:154) ~[spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
        ... 16 more
2020-05-04 19:04:32.694 [main] ERROR com.vmware.mangle.utils.exceptions.handler.MangleUncaughtExceptionHandler.printFullCoreDump (91) - \home\mangle\var\opt\mangle-tomcat\logs\mangle-thread-dump-2020-05-04-19-04-32-602.log
```

**Configuration information:**
 - Deployment Type: locally
 - Deployment Mode: single node
 - Client OS: Windows 10

**Comment by vhkilari** [comment]
The issue is straight forward. We expect the user to provide a base directory for Mangle application runtime. You can configure it using property
'server.tomcat.basedir=/home/mangle/var/opt/mangle-tomcat' available in https://github.com/vmware/mangle/blob/master/mangle-services/src/main/resources/application.properties

**Comment by lladhibhutall** [comment]
@vhkilari Cool, thanks! I didn't check in `application.properties`
The user actually doesnt have access to make any changes to /home.

I will close the issue.
