### ISSUE TITLE
Can't run mangle in docker

### ISSUE THREAD

**Issue by xnull** [vmware/mangle#38]
**Describe the bug**
I've been trying to run mangle in docker, and spring throws an exception and exits

**To Reproduce**
1. Go to 'terminal'
2. Click on '....', run `docker run -ti --rm -p 8080:8080 -p 8443:8443  mangleuser/mangle:2.0`

**Expected behavior**
Mangle runs

**Screenshots**

**Logs**
```
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1:9042] Cannot connect))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:268) ~[cassandra-driver-core-3.6.0.jar!/:?]
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:107) ~[cassandra-driver-core-3.6.0.jar!/:?]
	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1652) ~[cassandra-driver-core-3.6.0.jar!/:?]
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1571) ~[cassandra-driver-core-3.6.0.jar!/:?]
	at com.datastax.driver.core.Cluster.init(Cluster.java:208) ~[cassandra-driver-core-3.6.0.jar!/:?]
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:376) ~[cassandra-driver-core-3.6.0.jar!/:?]
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:355) ~[cassandra-driver-core-3.6.0.jar!/:?]
	at com.datastax.driver.core.Cluster.connect(Cluster.java:305) ~[cassandra-driver-core-3.6.0.jar!/:?]
	at com.vmware.mangle.services.cassandra.CassandraClusterFactoryBean.executeSpecsAndScripts(CassandraClusterFactoryBean.java:349) ~[classes!/:2.0.0]
	at com.vmware.mangle.services.cassandra.CassandraClusterFactoryBean.afterPropertiesSet(CassandraClusterFactoryBean.java:231) ~[classes!/:2.0.0]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1821) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1758) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:339) ~[spring-context-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at com.vmware.mangle.services.cassandra.CassandraConfig$$EnhancerBySpringCGLIB$$8edbffbd.cluster(<generated>) ~[classes!/:2.0.0]
	at com.vmware.mangle.services.cassandra.AbstractClusterConfiguration.getRequiredCluster(AbstractClusterConfiguration.java:58) ~[classes!/:2.0.0]
	at com.vmware.mangle.services.cassandra.CassandraConfig$$EnhancerBySpringCGLIB$$8edbffbd.CGLIB$getRequiredCluster$38(<generated>) ~[classes!/:2.0.0]
	at com.vmware.mangle.services.cassandra.CassandraConfig$$EnhancerBySpringCGLIB$$8edbffbd$$FastClassBySpringCGLIB$$c0de4937.invoke(<generated>) ~[classes!/:2.0.0]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at com.vmware.mangle.services.cassandra.CassandraConfig$$EnhancerBySpringCGLIB$$8edbffbd.getRequiredCluster(<generated>) ~[classes!/:2.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0-internal]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1305) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1144) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:394) ~[spring-context-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:366) ~[spring-context-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at com.vmware.mangle.services.cassandra.CassandraConfig$$EnhancerBySpringCGLIB$$8edbffbd.getRequiredCluster(<generated>) ~[classes!/:2.0.0]
	at com.vmware.mangle.services.cassandra.AbstractCassandraConfiguration.session(AbstractCassandraConfiguration.java:106) ~[classes!/:2.0.0]
	at com.vmware.mangle.services.cassandra.CassandraConfig$$EnhancerBySpringCGLIB$$8edbffbd.CGLIB$session$26(<generated>) ~[classes!/:2.0.0]
	at com.vmware.mangle.services.cassandra.CassandraConfig$$EnhancerBySpringCGLIB$$8edbffbd$$FastClassBySpringCGLIB$$c0de4937.invoke(<generated>) ~[classes!/:2.0.0]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at com.vmware.mangle.services.cassandra.CassandraConfig$$EnhancerBySpringCGLIB$$8edbffbd.session(<generated>) ~[classes!/:2.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0-internal]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
```

**Configuration information:**
 - Deployment Type: Container
 - Deployment Mode: Single Node
 - Client OS: iOS
 - Client Browser: chrome
 
**Additional context**
NA

**Comment by rpraveen-vmware** [comment]
Hi,
It seems mangle is unable to connect to cassandra at port 9042.
Do you have the cassandra container running..?
If not, 
could you please deploy the cassandra container:

docker run --name mangle-cassandradb -v /cassandra/storage/:/var/lib/cassandra -p 9042:9042 -d -e CASSANDRA_CLUSTER_NAME="manglecassandracluster" -e CASSANDRA_DC="DC1" -e CASSANDRA_RACK="rack1" -e CASSANDRA_ENDPOINT_SNITCH="GossipingPropertyFileSnitch" cassandra:3.11


And then add the cassandra db internal IP options in docker run for mangle container.

docker run --name mangle -d -e DB_OPTIONS="-DcassandraContactPoints=172.17.0.2 -DcassandraSslEnabled=true -DcassandraUsername=cassandra -DcassandraPassword=cassandra"  -e CLUSTER_OPTIONS="-DclusterValidationToken=mangle -DpublicAddress=127.0.0.1" -p 8080:8080 -p 443:8443 mangleuser/mangle:2.0

Please let us know if you face issues.

**Comment by rpraveen-vmware** [comment]
Hi,
Let me know if you are able to resolve this issue and can close this issue.

**Comment by xnull** [comment]
Hi, @rpraveen-vmware your answer helped me figure out how to run it on Mac os, thanks. One of the tricks is to define a custom network which provides domain name resolution inside the network.

Command lines:
```
#run mangle
docker run --rm -ti \
  --network=mangle-net \
  -e DB_OPTIONS="-DcassandraContactPoints=mangle-cassandradb -DcassandraSslEnabled=false" \
  -e CLUSTER_OPTIONS="-DclusterValidationToken=mangle -DpublicAddress=127.0.0.1" \
  -p 8080:8080 -p 8443:8443 \
  mangleuser/mangle:2.0
```

```
#run cassandra
docker run --name mangle-cassandradb --rm -ti  \
  -p 9042:9042 --hostname=cass --network=mangle-net \
  -e CASSANDRA_CLUSTER_NAME="manglecassandracluster" \
  -e CASSANDRA_DC="DC1" \
  -e CASSANDRA_RACK="rack1" -e CASSANDRA_ENDPOINT_SNITCH="GossipingPropertyFileSnitch" \
  cassandra:3.11
```

P.S. Unfortunately all this, is not clear from the documentation. 
I think it would be great to provide a docker-compose file in the documentation, which clearly shows how to run mangle.
For instance, [here is ELK compose file](https://github.com/deviantony/docker-elk/blob/master/docker-compose.yml)
